### PR TITLE
feat(extensions): Add support for task list extension

### PR DESCRIPTION
**Pull request by gillchristian**
Solves #15 

Added support for the task list extension.

As I mentioned in the issue I (kinda) don't know what I'm doing. But the test case passed so 🤷‍♂ 

I have two questions about my PR:

- I see that test cases are quite simple, I added one using the example from the spec (https://github.github.com/gfm/#task-list-items-extension-). Would that be the right test?
- I did not manage to run the benchmakrs (will try again later). Anyways, I added cases of task lists to `bench/full-sample.md`. Is that find? Do I have to do something about the benchmarks?

### CODE REVIEW

**Comment by kivikakk** [comment]
This looks perfect, honestly; thank you!

* The test looks fine — we don't need to be extensive, just make sure that the options are being passed through to the underlying library correctly. This does that ✅ 
* I don't know about the benchmarks, honestly — I've left them unchanged from the upstream [cmark-hs](https://github.com/jgm/cmark-hs). Adding the extensions does make sense, so this is good to merge ✅ 

Thank you so much!

**Comment by kivikakk** [comment]
Let me know if you'd like a version bump/new release on Hackage.

**Comment by gillchristian** [comment]
Wow already merged 😮 Thanks for the fast response 🎉

Yeah, the version bump would be great. But on the meantime I can install from GitHub, already tried that to double check if it was working.

**Comment by kivikakk** [comment]
Thanks for making it so easy to merge! 🚀 

0.2.1 is tagged and published on Hackage :+1:

**Pull request merged**
